### PR TITLE
Add IPU registers

### PR DESCRIPTION
**Pull request by zachary-cauchi**
* Add remaining fields to IPU registers.

### CODE REVIEW

**Comment by Ravenslofty** [comment]
You should probably rebase this branch on master.

**Comment by zachary-cauchi** [comment]
Just did, according to git, the branch is up-to-date with master. Already synced with master after the previous pr was merged. Have a habit of merging to sync instead of rebasing.

**Comment by Ravenslofty** [comment]
Are you sure it's up to date with *my* master and not simply yours? :p

**Comment by zachary-cauchi** [comment]
I first synced my fork with your master, then I did a git merge from my master into this branch. Lemme check and confirm just to be sure.

**Comment by Ravenslofty** [comment]
GitHub is showing your GIF commits as things to merge, but they're already in master.

**Comment by zachary-cauchi** [comment]
Maybe I can abandon the pr and branch, create a new one from master, then cherrypick the commits from this branch onto it?

**Comment by Ravenslofty** [comment]
That would work. Or alternatively I should have stuck to my principles and
rebase-and-merged your branch instead of just merging it like my coworkers
urge me to do.

**Comment by zachary-cauchi** [comment]
Ah, I see you too are a man of work culture. I'll begin the process then. I'll close this an open a new pr in a few minutes.

**Comment by Ravenslofty** [comment]
Sure. 

My name is Hannah by the way.

**Comment by zachary-cauchi** [comment]
Pleasure. I'm Zach (although that might have been obvious).

**Pull request closed without merging**
